require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '15.1'
use_modular_headers!
target 'Sahada' do
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath], :hermes_enabled => false)
  pod 'Firebase/Analytics', '10.20.0'
  pod 'Firebase/Auth', '10.20.0'
  pod 'Firebase/Functions', '10.20.0'
  pod 'Firebase/Messaging', '10.20.0'
  pod 'Firebase/Storage', '10.20.0'
  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++14'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        
        if target.name.start_with?('gRPC') || target.name == 'BoringSSL-GRPC'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end
      end
    end
  end
end
