# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.4'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Sahada' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase bağımlılıkları - SABİT VERSİYONLAR
  pod 'Firebase/Analytics', '~> 10.18.0'
  pod 'Firebase/Auth', '~> 10.18.0'
  pod 'Firebase/Firestore', '~> 10.18.0'
  pod 'Firebase/Functions', '~> 10.18.0'
  pod 'Firebase/Messaging', '~> 10.18.0'
  pod 'Firebase/Storage', '~> 10.18.0'

  # BoringSSL ve gRPC hataları için SABİT VERSİYONLAR
  pod 'gRPC-Core', '1.44.0', :modular_headers => true
  pod 'gRPC-C++', '1.44.0', :modular_headers => true
  
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1'
        
        if target.name == 'BoringSSL-GRPC'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'COCOAPODS=1']
        end
        
        if target.name.start_with?('gRPC')
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
        
        if target.name.include?('RNFB')
          config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
        
        if target.name == 'Flipper'
          file_path = File.join(config.build_settings['PODS_ROOT'], target.name)
          FileUtils.rm_rf(file_path) if File.exist?(file_path)
        end
      end
    end
  end
end
